### ISSUE TITLE
Step 6 in dev_app.py doesn't work. Where is the actual API? 

### ISSUE THREAD

**Issue by antsankov** [nathan-lapinski/Flask-REST-API#1]
When I try to execute the app with `./dev_app.py` as step 6 on line 19 of dev_app.py directs, I get the following output:

```
./dev_app.py: line 1: Nathan: command not found
./dev_app.py: line 3: This: command not found
./dev_app.py: line 4: Build: command not found
./dev_app.py: line 6: -Build: command not found
./dev_app.py: line 7: These: command not found
./dev_app.py: line 9: syntax error near unexpected token `)'
./dev_app.py: line 9: `1) mkdir rest-api'
```

This seems to obviously due to incorrect commenting. But even with proper commenting, I am still unable to find the actual API, all I see are some Curl tests. Where can I look to run the API itself?

**Comment by nt1-8** [comment]
Hey, thanks for catching that. I've pushed some new changes, so everything should be working now. Try executing dev_app.py again, and it should start the API.
Thanks!

**Comment by antsankov** [comment]
Looks good to me!

**Comment by nt1-8** [comment]
Great - I will close this then, but let me know if you run into anything else.
