### ISSUE TITLE
Dan Bye's Evaluation: dev.api (Again)

### ISSUE THREAD

**Issue by CaptainAtlas** [nathan-lapinski/Flask-REST-API#5]
I can't view the actual api either. Any chance there are changes that haven't been pushed?

**Comment by nt1-8** [comment]
Hi all, that's strange...it was working before I pushed it up. I'll look into this now and have updates in the next couple of hours.

**Comment by nt1-8** [comment]
Ok - should be up and running now - please let me know if you run into any issues with it. The README describes how to get it up and running.

**Comment by CaptainAtlas** [comment]
I think the main issue for me is the Readme. The code is good and I can tell what the service is doing very easily, I just don't know if my preferred method of running flask works for this project. Bottom line: Code looks good, I can tell what it's doing, so good work.

**Comment by CaptainAtlas** [comment]
Scratch that. I got it now. Thanks!
